# Generated by Django 5.1.2 on 2025-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='value',
            field=models.CharField(choices=[('like', 'Нравится'), ('dislike', 'Не нравится')], max_length=7, null=True),
        ),
    ]
